name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Ana dalınıza push edildiğinde bu iş akışı tetiklenir
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub'ın verdiği varsayılan token
          action: "upload"
          app_location: "/"  # React uygulamanızın kök dizini
          output_location: "build"  # React uygulamanızın derleme çıktısı
          env: 
            REACT_APP_AZURE_VISION_ENDPOINT: ${{ secrets.REACT_APP_AZURE_VISION_ENDPOINT }}
            REACT_APP_AZURE_VISION_KEY: ${{ secrets.REACT_APP_AZURE_VISION_KEY }}
            REACT_APP_OPENAI_API_KEY: ${{ secrets.REACT_APP_OPENAI_API_KEY }}
